### ISSUE TITLE
Talk about "SQL from the Client/Frontend"

### ISSUE THREAD

**Issue by davidgomes** [lisboajs/community#1]
I've been having a lot of discussions, and built some prototypes around the idea of building apps where the frontend is connecting directly to the database. There's a few different vendor-based solutions to this (SurrealDB, PostgREST/Supabase, Firebase, etc.), but each one comes with its own tradeoffs. I'd like to go over all these tradeoffs, with lots of accompanying code and demos.

**Comment by malikpiara** [comment]
Hi @davidgomes, the talk is set to take place on December 12th, along with @ahmedragabshaban who's coming all the way from Berlin. Thank you for being here and for sharing your knowledge with the community!

We'll start taking care of the event communication next week. Whenever you're ready, please share the following information with us, along with a photo we can use:

**Talk Title**
A clear and concise title for your proposed talk.

**Talk Description**
A brief description of what you'll cover in your talk (2-3 paragraphs max).

**Target Audience**
Who would benefit most from this talk? (e.g., beginners, intermediate developers, anyone interested in AI, etc.)

**Speaker Bio**
A short bio about yourself and your experience with the topic.

**Comment by davidgomes** [comment]
**Talk Title**
Is “SQL from the frontend” viable?

**Talk Description**
I’ve worked on apps with a “SQL from the client” architecture and the development velocity was simply superb. At the same time, it comes with a lot of challenges in terms of security and scalability. So, what’s the deal? Is it viable or not?

The tl;dr is that the technology is perhaps not ready yet, but it makes a lot of sense for a large swath of apps – especially prototypes. But this is a complex topic, and I’ll go deeper into the security problems in this talk.

**Target Audience**
Product engineers

**Speaker bio**
My name is David and I live in Madrid, Spain. My professional passion is Software Engineering, with a particular focus on Developer Tooling, AI and Big Data.

I am currently a Software Engineer at [Neon](https://neon.tech/?ref=davidgomes.com). We're enabling developers to ship faster with Postgres!

**Comment by davidgomes** [comment]
Second talk

**Talk Title**
Building a "Model Context Protocol" Server in Node.js

**Talk Description**
We'll show you how to quickly create a server for Anthropic's recently released Model Context Protocol using Node.js. We'll use Neon's recently published [MCP server](https://github.com/neondatabase/mcp-server-neon/) as a guiding example.

**Target Audience**
Anyone interested in building apps or services that LLMs and AI agents can integrate with.

**Speaker Bio**
David Gomes — My name is David and I live in Madrid, Spain. My professional passion is Software Engineering, with a particular focus on Developer Tooling, AI and Big Data.
Pedro Figueiredo — Software Engineer at Neon, interested in TypeScript, React and AI.

**Comment by pffigueiredo** [comment]
> Pedro Figueiredo — Software Engineer at Neon, interested in TypeScript, React and AI.

Hey, my name is Pedro Figueiredo. I'm a Software Engineer at Neon, and I'm mostly interested in TypeScript, Product Engineering, and, most recently, AI.
